CREATE TABLE ATENDENTE (
    ID_ATENDENTE NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    CODIGO_ACESSO VARCHAR2(255) NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    FK_TELEFONE_TELEFONE_PK NUMBER,
    EMAIL VARCHAR2(255)
);

CREATE TABLE GERENTE (
    ID_GERENTE NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    CODIGO_ACESSO VARCHAR2(255) NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    FK_TELEFONE_TELEFONE_PK NUMBER,
    EMAIL VARCHAR2(255)
);

CREATE TABLE SOCIO (
    ID_SOCIO NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    CEP VARCHAR2(10) NOT NULL,
    NUMERO NUMBER NOT NULL,
    RG VARCHAR2(20) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    OBSERVACOES VARCHAR2(4000),
    TELEFONE NUMBER,
    FK_ATENDENTE_ID_ATENDENTE NUMBER,
    FK_GERENTE_ID_GERENTE NUMBER
);

CREATE TABLE FILME (
    CODIGO_FILME NUMBER NOT NULL PRIMARY KEY,
    CATEGORIA VARCHAR2(255) NOT NULL,
    NOME_FILME VARCHAR2(255) NOT NULL,
    PARTICIPANTES NUMBER NOT NULL,
    PRODUTOR VARCHAR2(255),
    ANO_CRIACAO NUMBER NOT NULL,
    RESUMO VARCHAR2(4000),
    DURACAO_APROXIMADA VARCHAR2(50),
    FK_GERENTE_ID_GERENTE NUMBER
);

CREATE TABLE LOCACAO (
    CODIGO_LOCACAO NUMBER NOT NULL PRIMARY KEY,
    DATA_HORA_LOCACAO TIMESTAMP NOT NULL,
    DATA_PREVISTA_ENTREGA DATE NOT NULL,
    VALOR_LOCACAO_DIARIA NUMBER NOT NULL,
    DIAS_ATRASO NUMBER,
    VALOR_ACUMULADO NUMBER,
    STATUS VARCHAR2(50),
    FK_SOCIO_ID_SOCIO NUMBER NOT NULL,
    FK_FILME_CODIGO_FILME NUMBER NOT NULL,
    FK_RELATORIO_CODIGO_RELAT NUMBER
);

CREATE TABLE RESERVA (
    CODIGO_RESERVA NUMBER NOT NULL PRIMARY KEY,
    DATA_RESERVA DATE NOT NULL,
    STATUS VARCHAR2(50),
    FK_SOCIO_ID_SOCIO NUMBER NOT NULL,
    FK_FILME_CODIGO_FILME NUMBER NOT NULL
);

CREATE TABLE RELATORIO (
    CODIGO_RELAT NUMBER NOT NULL PRIMARY KEY,
    DATA_RELAT DATE NOT NULL,
    FATURAMENTO_TOTAL NUMBER NOT NULL,
    TIPO_RELAT NUMBER,
    FK_FATURAMENTO_CODIGO_FATURAMENTO NUMBER
);

CREATE TABLE FATURAMENTO (
    CODIGO_FATURAMENTO NUMBER NOT NULL PRIMARY KEY,
    DATA DATE NOT NULL,
    VALOR_TOTAL_DIA NUMBER NOT NULL,
    FK_CODIGO_RELATORIO NUMBER
);

CREATE TABLE TELEFONE (
    TELEFONE_PK NUMBER NOT NULL NOT NULL PRIMARY KEY,
    TELEFONE_1 NUMBER,
    TELEFONE_2 NUMBER
);

ALTER TABLE SOCIO 
ADD CONSTRAINT FK_SOCIO_2
FOREIGN KEY (FK_ATENDENTE_ID_ATENDENTE)
REFERENCES ATENDENTE (ID_ATENDENTE);

ALTER TABLE SOCIO 
ADD CONSTRAINT FK_SOCIO_3
FOREIGN KEY (FK_GERENTE_ID_GERENTE)
REFERENCES GERENTE (ID_GERENTE);

ALTER TABLE FILME 
ADD CONSTRAINT FK_FILME_2
FOREIGN KEY (FK_GERENTE_ID_GERENTE)
REFERENCES GERENTE (ID_GERENTE);

ALTER TABLE LOCACAO 
ADD CONSTRAINT FK_LOCACAO_2
FOREIGN KEY (FK_SOCIO_ID_SOCIO)
REFERENCES SOCIO (ID_SOCIO);

ALTER TABLE LOCACAO 
ADD CONSTRAINT FK_LOCACAO_3
FOREIGN KEY (FK_FILME_CODIGO_FILME)
REFERENCES FILME (CODIGO_FILME);

ALTER TABLE LOCACAO 
ADD CONSTRAINT FK_LOCACAO_4
FOREIGN KEY (FK_RELATORIO_CODIGO_RELAT)
REFERENCES RELATORIO (CODIGO_RELAT);

ALTER TABLE RESERVA 
ADD CONSTRAINT FK_RESERVA_2
FOREIGN KEY (FK_SOCIO_ID_SOCIO)
REFERENCES SOCIO (ID_SOCIO);

ALTER TABLE RESERVA 
ADD CONSTRAINT FK_RESERVA_3
FOREIGN KEY (FK_FILME_CODIGO_FILME)
REFERENCES FILME (CODIGO_FILME);

ALTER TABLE RELATORIO 
ADD CONSTRAINT FK_RELATORIO_2
FOREIGN KEY (FK_FATURAMENTO_CODIGO_FATURAMENTO)
REFERENCES FATURAMENTO (CODIGO_FATURAMENTO);

ALTER TABLE FATURAMENTO 
ADD CONSTRAINT FK_FATURAMENTO_2
FOREIGN KEY (FK_CODIGO_RELATORIO)
REFERENCES RELATORIO (CODIGO_RELAT);