CREATE TABLE ALUNO (
    ID_ALUNO NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    DATA_NASCIMENTO DATE,
    CEP VARCHAR2(9) NOT NULL,
    NUMERO NUMBER NOT NULL,
    FK_TELEFONE_TELEFONE_PK NUMBER,
    EMAIL VARCHAR2(50) NOT NULL,
    FK_ATENDENTE_ID_ATENDENTE NUMBER
);

CREATE TABLE ATENDENTE (
    ID_ATENDENTE NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE NUMBER NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL
);

CREATE TABLE CURSO (
    ID_CURSO NUMBER NOT NULL PRIMARY KEY,
    NOME_CURSO VARCHAR2(100) NOT NULL,
    CARGA_HORARIA NUMBER NOT NULL
);

CREATE TABLE TURMA (
    ID_TURMA NUMBER PRIMARY KEY,
    HORARIO_INICIO TIMESTAMP NOT NULL,
    HORARIO_TERMINO TIMESTAMP NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE NOT NULL,
    MINIMO_ALUNO NUMBER NOT NULL,
    MAXIMO_ALUNOS NUMBER NOT NULL,
    STATUS VARCHAR2(100) NOT NULL,
    FK_CURSO_ID_CURSO NUMBER NOT NULL
);

CREATE TABLE MATRICULA_FAZ (
    ID_MATRICULA NUMBER NOT NULL PRIMARY KEY,
    DATA_MATRICULA DATE NOT NULL,
    STATUS VARCHAR2(100) NOT NULL,
    FK_ALUNO_ID_ALUNO NUMBER NOT NULL,
    FK_TURMA_ID_TURMA NUMBER NOT NULL
);

CREATE TABLE TELEFONE (
    TELEFONE_PK NUMBER NOT NULL PRIMARY KEY,
    TELEFONE_1 NUMBER NOT NULL,
    TELEFONE_2 NUMBER
);
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_2
    FOREIGN KEY (FK_TELEFONE_TELEFONE_PK)
    REFERENCES TELEFONE (TELEFONE_PK)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_3
    FOREIGN KEY (FK_ATENDENTE_ID_ATENDENTE)
    REFERENCES ATENDENTE (ID_ATENDENTE);

ALTER TABLE TURMA ADD CONSTRAINT FK_TURMA_2
    FOREIGN KEY (FK_CURSO_ID_CURSO)
    REFERENCES CURSO (ID_CURSO);
 
ALTER TABLE MATRICULA_FAZ ADD CONSTRAINT FK_MATRICULA_FAZ_2
    FOREIGN KEY (FK_ALUNO_ID_ALUNO)
    REFERENCES ALUNO (ID_ALUNO);

ALTER TABLE MATRICULA_FAZ ADD CONSTRAINT FK_MATRICULA_FAZ_3
    FOREIGN KEY (FK_TURMA_ID_TURMA)
    REFERENCES TURMA (ID_TURMA);