
CREATE TABLE SOLICITANTE (
    ID_SOLICITANTE NUMBER PRIMARY KEY,
    NOME VARCHAR2(255),
    SENHA VARCHAR2(255)
);

CREATE TABLE TECNICO (
    ID_TECNICO NUMBER PRIMARY KEY,
    NOME VARCHAR2(255),
    SENHA VARCHAR2(255)
);

CREATE TABLE CHAMADO (
    ID_CHAMADO NUMBER PRIMARY KEY,
    DATA_ABERTURA DATE,
    DATA_CONCLUSAO DATE,
    ESTADO VARCHAR2(20),
    DESCRICAO_PROBLEMA VARCHAR2(500),
    DESCRICAO_PROVIDENCIAS VARCHAR2(500),
    FK_SOLICITANTE_ID_SOLICITANTE NUMBER,
    FK_TECNICO_ID_TECNICO NUMBER,
    CONSTRAINT FK_CHAMADO_SOLICITANTE FOREIGN KEY (FK_SOLICITANTE_ID_SOLICITANTE)
        REFERENCES SOLICITANTE (ID_SOLICITANTE),
    CONSTRAINT FK_CHAMADO_TECNICO FOREIGN KEY (FK_TECNICO_ID_TECNICO)
        REFERENCES TECNICO (ID_TECNICO)
);

CREATE TABLE HISTORICO (
    ID_HISTORICO NUMBER PRIMARY KEY,
    DATA_ATUALIZACAO DATE,
    DESCRICAO_ATUALIZACAO VARCHAR2(500),
    FK_CHAMADO_ID_CHAMADO NUMBER,
    FK_TECNICO_ID_TECNICO NUMBER,
    CONSTRAINT FK_HISTORICO_CHAMADO FOREIGN KEY (FK_CHAMADO_ID_CHAMADO)
        REFERENCES CHAMADO (ID_CHAMADO),
    CONSTRAINT FK_HISTORICO_TECNICO FOREIGN KEY (FK_TECNICO_ID_TECNICO)
        REFERENCES TECNICO (ID_TECNICO)
);

CREATE TABLE LOGIN (
    ID_LOGIN NUMBER PRIMARY KEY,
    MATRICULA_USUARIO NUMBER,
    DATA_LOGIN DATE,
    TIPO_USUARIO VARCHAR2(20),
    FK_SOLICITANTE_ID_SOLICITANTE NUMBER,
    FK_TECNICO_ID_TECNICO NUMBER,
    CONSTRAINT FK_LOGIN_SOLICITANTE FOREIGN KEY (FK_SOLICITANTE_ID_SOLICITANTE)
        REFERENCES SOLICITANTE (ID_SOLICITANTE),
    CONSTRAINT FK_LOGIN_TECNICO FOREIGN KEY (FK_TECNICO_ID_TECNICO)
        REFERENCES TECNICO (ID_TECNICO)
);