CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER NOT NULL PRIMARY KEY,
    FK_ID_SECRETARIA NUMBER NOT NULL,
    FK_TELEFONE_TELEFONE_PK NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CEP VARCHAR2(10) NOT NULL,
    NUMERO NUMBER NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    DATA_CADASTRO DATE NOT NULL
);

CREATE TABLE ANIMAL (
    ID_ANIMAL NUMBER NOT NULL PRIMARY KEY,
    FK_CLIENTE_ID_CLIENTE NUMBER NOT NULL,
    FK_ESPECIE NUMBER NOT NULL,
    FK_ID_SECRETARIA NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    RACA VARCHAR2(50) NOT NULL,
    IDADE NUMBER NOT NULL,
    DATA_CAD DATE NOT NULL
);

CREATE TABLE CONSULTA (
    ID_CONSULTA NUMBER NOT NULL PRIMARY KEY,
    FK_ID_VETERINARIO NUMBER NOT NULL,
    FK_ID_ANIMAL NUMBER NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    SINTOMAS VARCHAR2(4000) NOT NULL,
    DIAGNOSTICO VARCHAR2(4000)
);

CREATE TABLE VETERINARIO (
    ID_VETERINARIO NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ESPECIALIDADE VARCHAR2(100) NOT NULL,
    CRMV VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    FK_TELEFONE_TELEFONE_PK NUMBER NOT NULL,
    FK_SECRETARIA_ID_SECRETARIA NUMBER NOT NULL
);

CREATE TABLE EXAME (
    ID_EXAME NUMBER NOT NULL PRIMARY KEY,
    FK_ID_CONSULTA NUMBER NOT NULL,
    FK_ID_ANIMAL NUMBER NOT NULL,
    TIPO_EXAME VARCHAR2(100) NOT NULL,
    DATA_EXAME DATE NOT NULL,
    RESULTADO VARCHAR2(4000)
);

CREATE TABLE HISTORICO_TRAT (
    ID_HISTORICO NUMBER NOT NULL PRIMARY KEY,
    FK_ID_ANIMAL NUMBER NOT NULL,
    FK_ID_CONSULTA NUMBER NOT NULL,
    DETALHES_TRATAMENTO VARCHAR2(4000) NOT NULL,
    OBSERVACOES VARCHAR2(4000)
);

CREATE TABLE CONTA_RECEBER (
    ID_CONTA NUMBER NOT NULL PRIMARY KEY,
    FK_ID_CLIENTE NUMBER NOT NULL,
    FK_ID_CONSULTA NUMBER NOT NULL,
    VALOR NUMBER NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL
);

CREATE TABLE ESPECIE (
    ID_ESPECIE NUMBER NOT NULL PRIMARY KEY,
    FK_ID_SECRETARIA NUMBER NOT NULL,
    NOME_ESPECIE VARCHAR2(100) NOT NULL
);

CREATE TABLE SECRETARIA (
    ID_SECRETARIA NUMBER NOT NULL PRIMARY KEY,
    TELEFONE NUMBER NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL
);

CREATE TABLE TELEFONE (
    TELEFONE_PK NUMBER NOT NULL NOT NULL PRIMARY KEY,
    TELEFONE_1 VARCHAR2(15) NOT NULL,
    TELEFONE_2 VARCHAR2(15)
);


ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_SECRETARIA
    FOREIGN KEY (FK_ID_SECRETARIA)
    REFERENCES SECRETARIA (ID_SECRETARIA);

ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL_CLIENTE
    FOREIGN KEY (FK_CLIENTE_ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL_SECRETARIA
    FOREIGN KEY (FK_ID_SECRETARIA)
    REFERENCES SECRETARIA (ID_SECRETARIA);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_ANIMAL
    FOREIGN KEY (FK_ID_ANIMAL)
    REFERENCES ANIMAL (ID_ANIMAL);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_VETERINARIO
    FOREIGN KEY (FK_ID_VETERINARIO)
    REFERENCES VETERINARIO (ID_VETERINARIO);

ALTER TABLE EXAME ADD CONSTRAINT FK_EXAME_CONSULTA
    FOREIGN KEY (FK_ID_CONSULTA)
    REFERENCES CONSULTA (ID_CONSULTA);

ALTER TABLE EXAME ADD CONSTRAINT FK_EXAME_ANIMAL
    FOREIGN KEY (FK_ID_ANIMAL)
    REFERENCES ANIMAL (ID_ANIMAL);

ALTER TABLE HISTORICO_TRAT ADD CONSTRAINT FK_HISTORICO_TRAT_ANIMAL
    FOREIGN KEY (FK_ID_ANIMAL)
    REFERENCES ANIMAL (ID_ANIMAL);

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_CLIENTE
    FOREIGN KEY (FK_ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE ESPECIE ADD CONSTRAINT FK_ESPECIE_SECRETARIA
    FOREIGN KEY (FK_ID_SECRETARIA)
    REFERENCES SECRETARIA (ID_SECRETARIA);

