
CREATE TABLE CLIENTE (
    CLIENTE_ID NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    FK_TELEFONE_TELEFONE_PK NUMBER NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CEP VARCHAR2(8) NOT NULL,
    NUMERO NUMBER NOT NULL
);

CREATE TABLE VOO (
    VOO_ID NUMBER NOT NULL PRIMARY KEY,
    FK_ORIGEM_AEROPORTO_ID NUMBER NOT NULL,
    FK_DESTINO_AEROPORTO_ID NUMBER NOT NULL,
    DATA_PARTIDA DATE NOT NULL,
    HORARIO_PARTIDA TIMESTAMP NOT NULL,
    DATA_RETORNO DATE, -- Pode ser NULL se for apenas ida
    HORARIO_RETORNO TIMESTAMP, -- Pode ser NULL se for apenas ida também
    PRECO NUMBER(10, 2) NOT NULL,
    CLASSE VARCHAR2(20) NOT NULL
);

CREATE TABLE AEROPORTO (
    AEROPORTO_ID NUMBER NOT NULL PRIMARY KEY,
    CODIGO_AEROPORTO VARCHAR2(10) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    ESTADO VARCHAR2(2) NOT NULL,
    PAIS VARCHAR2(50) NOT NULL
);

CREATE TABLE POLTRONA (
    POLTRONA_ID NUMBER NOT NULL PRIMARY KEY,
    FK_VOO_ID NUMBER NOT NULL,
    NUMERO_POLTRONA NUMBER NOT NULL,
    STATUS VARCHAR2(25) NOT NULL,
    CLASSE VARCHAR2(25) NOT NULL
);

CREATE TABLE PASSAGEM (
    PASSAGEM_ID NUMBER NOT NULL PRIMARY KEY,
    FK_CLIENTE_ID NUMBER NOT NULL,
    FK_VOO_ID NUMBER NOT NULL,
    FK_POLTRONA_ID NUMBER NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    DATA_COMPRA DATE NOT NULL,
    VALOR NUMBER(10, 2) NOT NULL,
    PARCELAS NUMBER NOT NULL
);

CREATE TABLE PAGAMENTO (
    PAGAMENTO_ID NUMBER NOT NULL PRIMARY KEY,
    FK_PASSAGEM_ID NUMBER NOT NULL,
    FORMA_PAGAMENTO VARCHAR2(20) NOT NULL,
    NUMERO_PARCELAS NUMBER NOT NULL
);

CREATE TABLE TELEFONE (
    TELEFONE_PK NUMBER NOT NULL PRIMARY KEY,
    TELEFONE_1 VARCHAR2(15) NOT NULL,
    TELEFONE_2 VARCHAR2(15)
);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_TELEFONE
    FOREIGN KEY (FK_TELEFONE_TELEFONE_PK)
    REFERENCES TELEFONE (TELEFONE_PK)
    ON DELETE CASCADE;

ALTER TABLE VOO ADD CONSTRAINT FK_VOO_ORIGEM_AEROPORTO
    FOREIGN KEY (FK_ORIGEM_AEROPORTO_ID)
    REFERENCES AEROPORTO (AEROPORTO_ID);

ALTER TABLE VOO ADD CONSTRAINT FK_VOO_DESTINO_AEROPORTO
    FOREIGN KEY (FK_DESTINO_AEROPORTO_ID)
    REFERENCES AEROPORTO (AEROPORTO_ID);

ALTER TABLE POLTRONA ADD CONSTRAINT FK_POLTRONA_VOO
    FOREIGN KEY (FK_VOO_ID)
    REFERENCES VOO (VOO_ID);

ALTER TABLE PASSAGEM ADD CONSTRAINT FK_PASSAGEM_CLIENTE
    FOREIGN KEY (FK_CLIENTE_ID)
    REFERENCES CLIENTE (CLIENTE_ID);

ALTER TABLE PASSAGEM ADD CONSTRAINT FK_PASSAGEM_VOO
    FOREIGN KEY (FK_VOO_ID)
    REFERENCES VOO (VOO_ID);

ALTER TABLE PASSAGEM ADD CONSTRAINT FK_PASSAGEM_POLTRONA
    FOREIGN KEY (FK_POLTRONA_ID)
    REFERENCES POLTRONA (POLTRONA_ID);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_PASSAGEM
    FOREIGN KEY (FK_PASSAGEM_ID)
    REFERENCES PASSAGEM (PASSAGEM_ID);